spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/statement
    username: root
    password: 1234

#  sql:
#    init:
#      platform: mysql
#      continue-on-error: false
#      mode: always
#      schema-locations: chapter10/schema-mysql.sql

#  batch:
#    jdbc:
#      initialize-schema: always

#    job:
#      names: transactionsssJob

  jpa:
    show-sql: true
    hibernate:
      naming:
        implicit-strategy: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

#  data:
#    mongodb:
#      database: customerdb

  jms:
    template:
      default-destination: customers
      receive-timeout: 5000
  activemq:
    packages:
      trust-all: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'test'
    password: 'test'
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true